### ISSUE TITLE
Create Subscription | Issues while trying to create new subscription and using , instead of . 

### ISSUE THREAD

**Issue by byCoba** [BudgetBuddyDE/Webapp#10]
![Screenshot 2022-08-13 214443](https://user-images.githubusercontent.com/86473040/184508582-dfd05a53-d7aa-4c5e-911e-61e4faaec1fb.png)

**Comment by tklein1801** [comment]
@byCoba der Fehler wurde behoben 😄 
Du kannst nun Problemlos Zahlen mimt Komma oder mit Punkt im positiven sowie negativen Bereich auf mobilen und Desktop-Geräten eintragen.
